spring.application.name=springBootAngularAuth

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springBootPostgres
    username: mason
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 197b7f1cbd1e12ffe18c5192977d413351e817b63359649925eda70340f503bd
  expiration: 31536000000  # 1 year in ms