spring.application.name=springBootAngularAuth

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login_flow_db
    username: your_db_user
    password: your_db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your-256-bit-secret-key-here
  expiration: 86400000  # 24 hours in ms