spring.datasource.url=jdbc:postgresql://postgres:5432/springBootPostgres
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=197b7f1cbd1e12ffe18c5192977d413351e817b63359649925eda70340f503bd
jwt.expiration=31536000000
